### ISSUE TITLE
写css只能用less或者sass？

### ISSUE THREAD

**Issue by yuu2lee4** [imochen/hotcss#10]
不能直接在css文件里写？？

**Comment by imochen** [comment]
less、scss只是方便将px转化为rem。并且源文件中能保留你的原始值。
不使用less，scss的话，可以自己手动将px转化为rem。
暂时没有提供postcss转化方法，可以自行实现。

**Comment by yuu2lee4** [comment]
/*
 design_w:初始化（效果图）宽度，
 maxW:最大页面宽度，超过这个宽度html fontsize不再变化 建议跟设计图宽度一样
 minW:最小页面宽度，小于这个宽度html fontsize不再变化 建议为320
 default_fz：初始化页面html字体大小
 说明： 最好在body加载之前执行
 */
var htmladapt = {
    opt:{
        design_w:720,
        maxW:0,
        minW:0,
        default_fz:100
    },
    htmlObj:document.getElementsByTagName('html')[0],
    init:function (option){
        var self = this;
        this.extend(this.opt,option);
        this.setHtmlFontSize();

```
    window.addEventListener('resize',function(){
        self.setHtmlFontSize();
    },false)
},
setHtmlFontSize:function(){
    var opt = this.opt,fz;
    var base = win_width = window.outerWidth;

    if(opt.maxW && win_width > opt.maxW){//最大值
        base = opt.maxW;
    }
    if(opt.minW && win_width < opt.minW){//最小值
        base = opt.minW;
    }

    fz = (base/opt.design_w)*opt.default_fz;
    this.htmlObj.style.fontSize = fz+'px';
},
extend:function(o,n){
    for(var p in n){
        if(n.hasOwnProperty(p) || !o.hasOwnProperty(p)){
            o[p]=n[p];
        }
    }
},
getStyle:function(obj, attr) {
    return obj.currentStyle ? obj.currentStyle[attr] : getComputedStyle(obj,false)[attr];
}
```

}

用法
htmladapt.init({design_w:720,maxW:720, minW:320});
求指教

**Comment by imochen** [comment]
你要问什么？你加这个群吧130977811
