### ISSUE TITLE
ios上微信会出现blink的bug

### ISSUE THREAD

**Issue by xiongchengqing** [imochen/hotcss#11]
ios上微信会出现blink的bug

**Comment by emotiony** [comment]
![1](https://cloud.githubusercontent.com/assets/1636616/12474386/cdb2f05a-c055-11e5-96c5-cefcc555b840.gif)

**Comment by xiongchengqing** [comment]
![3islrdsj0w](https://cloud.githubusercontent.com/assets/1636616/12474504/acb849d0-c056-11e5-86b7-55f6a975d756.gif)

**Comment by mybulesea** [comment]
WHAT!

**Comment by xiongchengqing** [comment]
刚刚贴了一张gif上了，复现了一下

**Comment by xiongchengqing** [comment]
@imochen 不知道作者有没有遇到这种现象，当在ios微信中刷新页面或者异步加载列表时，页面样式会突然乱掉然后正常

**Comment by imochen** [comment]
确认下hotcss.js是否是异步加载。或者在其他JS后面加载。
刷新闪烁这个现象是由于需要JS解析去修改font-size和dpr。

如果是固定dpr。可以预先手写meta viewport。以及定义一个初始的html font-size。**可以缓解。**
