### ISSUE TITLE
normal example中的body:16rem;

### ISSUE THREAD

**Issue by think2011** [imochen/hotcss#12]
请问这个 `16rem` 是什么意思呢？

**Comment by think2011** [comment]
另外请问 `$px*320/$designWidth/20 + rem;` 这里的320和20是什么意思呢？ 有相关的文章解释吗？

**Comment by imochen** [comment]
- 16rem。相当于设计稿的100%。
- 320是认为页面是320像素。
- 20是每份的的宽度。因为10px在某些浏览器无法显示（最小12px）所以选择了每份20。据此可推断，16份即为320px。也即我们认为的页面宽度。

**Comment by think2011** [comment]
谢谢！知道了
