### ISSUE TITLE
微信下的一个兼容问题

### ISSUE THREAD

**Issue by Double-Lv** [imochen/hotcss#14]
在mresize方法中，获取window.innerWidth存在兼容问题，在微信下，横向转屏，然后再转成竖向之后，获取到的值有问题。
改为如下写法没问题了：
var innerWidth = document.documentElement.clientWidth || document.body.clientWidth;

**Comment by imochen** [comment]
获取`innerWidth`的方法已经修改为

```
var innerWidth = document.documentElement.getBoundingClientRect().width || window.innerWidth;
```
