### ISSUE TITLE
小米note下计算错误

### ISSUE THREAD

**Issue by js571** [imochen/hotcss#15]
使用px时，小米各机型会出现不同问题

小米note:

![](http://ww4.sinaimg.cn/large/c1b3b4e7gw1f1ckqbjcdcj20hr0vkabn.jpg)

红米note2: 

![](http://ww2.sinaimg.cn/large/c1b3b4e7gw1f1ckrto1jvj21kw23u1kx.jpg)

**Comment by imochen** [comment]
mark。暂时没有设备。待搞明白后再回复。您也可以自己调试下，看下原因。

**Comment by js571** [comment]
小米note是因为 dpr是3.5，然后示例代码中只写了dpr:1,2,3 的 font-size，所以表现不正常；

红米note2那个有可能是因为 老得MIUI系统的问题， viewport设置了scale对它无效，参考地址:  [MIUI 浏览器中 <meta> "viewport" 标签缩放无效](http://www.miui.com/thread-1758264-1-1.html) 。

**Comment by imochen** [comment]
感谢反馈，这种情况建议 字体直接使用rem，针对scale不支持小数的情况可以强制dpr=1。后续抽空我更新一下。

**Comment by imochen** [comment]
@js571 最新版本已经优化dpr。避免非整数的情况。

```
dpr = dpr >= 3 ? 3 : ( dpr >=2 ? 2 : 1 );
```
