### ISSUE TITLE
ios系统更新9.3后微信bug

### ISSUE THREAD

**Issue by MeCKodo** [imochen/hotcss#19]
iphone6 系统更新到9.3后，用了hotcss屏幕就可以横向拖拽，就像是宽度超过100%一样

**Comment by imochen** [comment]
可以通过调试工具具体查看一下。由于作者目前手头没有太多机型，不能完全测试。感谢你的反馈。
建议先自己调试下。
待我这边有结果后再在此处更新。

@todo

**Comment by MeCKodo** [comment]
下午仔细测了下， 无论是5还是5s还是6s 只要更新了9.3，在微信里都有问题

**Comment by imochen** [comment]
手淘的 flexible 在1月份也遇到了 ios9.3的 bug。根据他们的描述猜测。你强制dpr=1试试能否解决问题。

**Comment by imochen** [comment]
哈哈。刚刚实测了一下demo。并没有问题。是否能提供一个演示
