### ISSUE TITLE
怎么解决微信二维码问题？

### ISSUE THREAD

**Issue by dctxf** [imochen/hotcss#2]
什么方法能够解决微信长按扫描二维码？

**Comment by imochen** [comment]
使用hotcss2.0版本。在引入hotcss.js之前。强制定义dpr为1。可以解决iphone微信中无法识别二维码的问题。

```
<meta name="hotcss" content="initial-dpr=1">
```

注意：强制设置dpr之后。无法使用真实的1px。在2倍屏/3倍屏下。1px不再是真实的1px。

**Comment by Cheese-jmj** [comment]
页面在微信中打开，长按二维码也是同样的解决方式吗？我用了这个<meta name="hotcss" content="initial-dpr=1">，直接写img标签，可以长按二维码关注，但是只能在二维码的底部位置才有效，其他位置还是没有用。如果我在img上套了一层div，不加任何样式的话还是不能长按识别。这是什么原因。（即使不加initial-dpr，在安卓手机上是可以识别）

**Comment by imochen** [comment]
@Cheese-jmj 可以认为是微信webview的问题。
