### ISSUE TITLE
当一个元素文字，字数多的情况和文字字数少的情况下设置字体大小会出现问题

### ISSUE THREAD

**Issue by ninetybang2022** [imochen/hotcss#27]
同样的元素，设置字体大小，文字内容。在文字多的情况下和文字少的情况下
会出现文字大小不一致。也就是文字小的文字大小和文字多的文字大小不一致

**Comment by imochen** [comment]
#13

**Comment by ninetybang2022** [comment]
已经解决谢谢

2016-10-20 11:16 GMT+08:00 墨尘 notifications@github.com:
