### ISSUE TITLE
请问如何在fis3中使用 px2rem.less ？

### ISSUE THREAD

**Issue by slip-box** [imochen/hotcss#31]
less文件编译用的是[fis-parser-less](https://github.com/fouber/fis-parser-less)，感觉px2rem.less没有起效，fis3的用户有碰到此问题的吗？

**Comment by imochen** [comment]
- 更换`fis-parser-less`为新版的 [fis-parser-less-2.x](https://www.npmjs.com/package/fis-parser-less-2.x)
- 安装 [less-plugin-functions](https://www.npmjs.com/package/less-plugin-functions)
- 修改`fis-conf.js`中的less parser。参考以下代码

``` javascript
var LessPluginFunctions = require('less-plugin-functions');

fis.match('*.less',{
  parser: fis.plugin('less-2.x',{
    plugins:[new LessPluginFunctions()]
  }),
  rExt: '.css'
})
```

注：对FIS不很熟悉，以上自测没有问题，任何其他问题随时提问。

**Comment by slip-box** [comment]
赞！问题已解决。

**Comment by slip-box** [comment]
// 使用less时的px2rem，定义100px长度：px2rem(100);感觉太长？可简化为p(100)
.function {
    .px2rem(@x) {
        return: @x * 320/@designWidth/20rem;
    }
    .p(@x) {
        return: @x * 320/@designWidth/20rem;
    }
}
@designWidth:750;

**Comment by imochen** [comment]
这个是你自己控制的，觉得麻烦得话可以自己调整一下。
建议是不要调整。可以给编辑器设置代码片段。
