### ISSUE TITLE
安卓的dpr靠谱么？

### ISSUE THREAD

**Issue by hxlniada** [imochen/hotcss#32]
对比了一下hotcss和淘宝的flexible，看起来最大的不同就是你们考虑了安卓的dpr（不知道对不对）。
这个在实际中没遇到什么问题么？

**Comment by imochen** [comment]
不靠谱。如果不能预期安卓webview环境。建议直接上`initial-dpr=1`

**Comment by imochen** [comment]
hotcss之所以这么设计是因为有些需求，仅仅跑在自己app的webview中，可以改善1px的视觉效果。
