### ISSUE TITLE
js动态设置font-size和你们的解决方案有什么区别吗？

### ISSUE THREAD

**Issue by shenfusheng** [imochen/hotcss#33]
![image](https://cloud.githubusercontent.com/assets/9476838/21339166/fdb76a4c-c6b7-11e6-93f8-3e0878512890.png)
图中的7.2就是设计稿大小为720，如果是640的设计稿可以改成6.4，这样1rem=100px;比如有个div高度为80px，则css中可以这样子写div{height: 0.8rem;},这个和你们这种解决方案有什么区别吗

**Comment by imochen** [comment]
原理是一样的。要考虑到实际应用。

**Comment by shenfusheng** [comment]
@imochen 可以稍微解释清楚一下吗，我说的那种办法有什么缺点，我自己有在手机上对比了我说的方案和hotcss的方案，肉眼没看出来有什么区别

**Comment by imochen** [comment]
你这个叫方法。`flexible`和`hotcss`叫方案。区别就是方法仅需要考虑我现在能不能用。方案要考虑项目周期内90%以上的实际开发情况。

**Comment by kkkkkcnm** [comment]
??


原始邮件
发件人:墨尘notifications@github.com
收件人:imochen/hotcsshotcss@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2016年12月23日(周五) 19:22
主题:Re: [imochen/hotcss] js动态设置font-size和你们的解决方案有什么区别吗？ (#33)


Closed #33.
