### ISSUE TITLE
请问怎么配合postcss-plugin-px2rem使用

### ISSUE THREAD

**Issue by panhezeng** [imochen/hotcss#39]
我现在的项目使用的vux组件框架，webpack和vue-loader，我看hotcss的px2rem的转换公式是$px*320/$designWidth/20 + rem，和那些postcss的px2rem的插件公式都不一样。

**Comment by imochen** [comment]
```
rootValue = $designWidth*20/320;
```
试试这个配置。如果你的设计图是 640 。 rootValue = 40; 
按照上面公式计算即可。

**Comment by panhezeng** [comment]
postcss px2rem的换算公式
```// get calculated value of px or rem
Px2rem.prototype._getCalcValue = function (type, value, dpr) {
  var config = this.config;
  var pxGlobalRegExp = new RegExp(pxRegExp.source, 'g');

  function getValue(val) {
    val = parseFloat(val.toFixed(config.remPrecision)); // control decimal precision of the calculated value
    return val == 0 ? val : val + type;
  }

  return value.replace(pxGlobalRegExp, function ($0, $1) {
    return type === 'px' ? getValue($1 * dpr / config.baseDpr) : getValue($1 / config.remUnit);
  });
};
```

如果按手淘Flexiblejs的公式，设计稿750，px2rem的remUnit是75
如果用hotcss，px2rem的remUnit就不能是75了，是不是remUnit的单位按
`remUnit = $designWidth*20/320;`
就是对的了？
我算了一下，如果设计稿750，hotcss的750px经过公式
`parseInt(px,10)*320/designWidth/20`
换算为16rem
如果px2rem的remUnit值按公式
`remUnit = $designWidth*20/320;`
计算得到为46.875
则postcss px2rem插件的计算为750/46.875=16rem
这样就对上了，是吧。

**Comment by panhezeng** [comment]
经过在项目中实践
设计稿为750px
vue-loader配置为
```
postcss: [
    require('postcss-px2rem')({remUnit: 46.875})
  ]
```
插件转换后的rem值和hotcss提供的px2rem方法转换的值是一致的。
多谢：）

**Comment by imochen** [comment]
ok

**Comment by Amling2017** [comment]
vue中如何安装了这个依赖postcss-px2rem,那么文中的remUnit，如何通过设计图的尺寸计算得到，请各位大神指教！如果我的设计图是640或者750，那么它们对应的remUnit的值应该如何计算，求方法，谢谢！
