### ISSUE TITLE
font-size问题？

### ISSUE THREAD

**Issue by shenxinle** [imochen/hotcss#4]
font-size 也用 rem 的话，宽屏、窄屏上字号相差太大。
可能要根据 device-pixel-ratio 设置 body 的font-size，内容的font-size都使用 em。

**Comment by imochen** [comment]
感谢关注。hotcss是一个整体缩放方案(视觉一致)，不会出现字体过大的情况。关于提到的宽屏字体问题，待尝试后再来补充。@todo

**Comment by zhanqiancheng** [comment]
hi  @imochen ， 雪碧图用rem单位的话你们是用什么方案解决的？

**Comment by agileago** [comment]
字体大小用rem不太合适，比如我750的设计稿，量的字体大小是16px,经过hotcss进行缩放，在iphone5上字体就不是16px了，会变成12px, 会变小，这个字体大小无论怎么缩放应该在每个机器上的大小应该是一致的才对

**Comment by imochen** [comment]
@zhanqiancheng 
雪碧图不能用rem.rem定位不准确。正确做法是。用js判断缩放比例。
background-size 和 position都用px写死。
然后动态增加.zoom{transform:scale(xxx)}样式。
把使用到雪碧图的元素用zoom缩放。
绝对不能在雪碧图用rem定位。
小图建议base64

---- 来自前端早读课读者评论

我们不使用雪碧图，因为适配雪碧图并不合适

[相关文章](https://mp.weixin.qq.com/s?__biz=MjM5MTA1MjAxMQ==&mid=401350038&idx=1&sn=635d7614a263a806b191226fcb9148a7&scene=1&srcid=1224OQxR0wuGsr1ArT9h3Bk8&key=62bb001fdbc364e55784dcd3e86d9be21cf0eb37944a73ec54a0af21360073e2104c653f313a75ce0abec469f1e04dda&ascene=0&uin=MTI3MTQzODk0MA%3D%3D&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.11.2+build%2815C50%29&version=11020201&pass_ticket=rmSWcb8rhfpWFBRDAezkx2vMaXPbUAXGQddI8jopOvb1dSkz%2FnZaWw2%2FW8PmaoRg)

**Comment by imochen** [comment]
@agileago @shenxinle 关于hotcss中不使用rem的解决办法已经在最新的更新中增加了。

```
#container{
    font-size: 12px ;
    [data-dpr="2"] &{
        font-size: 24px;
    }
    [data-dpr="3"] &{
        font-size: 36px;
    }
}
```

但是我本人仍然不推荐这中limit处理，哈哈。违背了设计一致性原则。
另外@agileago 750设计稿下16px确实很小。

**Comment by agileago** [comment]
现在正在尝试用在生产环境中，其他方面都挺好，但是在页面上某一部分内容是后台富文本编辑器生成的内容，这一部分内容无法掌控，该怎么处理？

**Comment by agileago** [comment]
目前解决方案是强制设置

```
<meta name="hotcss" content="initial-dpr=1">
```

**Comment by imochen** [comment]
@agileago 是的，最简单的做法是强制dpr。然后按px显示即可。

我们曾经有一个这样的需求，是把富文本内容的尺寸转为了rem。但是效果并不怎么好，默认样式太多。所以就放弃了。强制了dpr=1。放弃了使用1px。

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
雪碧图 百分比定位就好啦
