### ISSUE TITLE
meta自动添加缺少iPhone X的适配

### ISSUE THREAD

**Issue by qkzzxb** [imochen/hotcss#43]
自定义name="viewport" meta无效
在hotcss.jsmeta中加入 viewport-fit=cover才行

**Comment by gdutwyg** [comment]
是不是不维护了？

**Comment by qkzzxb** [comment]
> 是不是不维护了？

现在各种刘海屏 打孔屏 水滴屏 伤不起

**Comment by imochen** [comment]
考虑整体更新一下。如提到的`viewport-fit=cover`问题。如需要，可先自行在自己的项目里fix。
