### ISSUE TITLE
hotcss.js 算是不是有点问题

### ISSUE THREAD

**Issue by petersam11** [imochen/hotcss#49]
我用 postcss-px2rem  remunit 设置为 37.5 即是一倍图, 在iphone6模式下, 我设置40px字体大小, 显示出来不是40px大小呀, 用flexible.js的话就是40px的

**Comment by imochen** [comment]
那应该不至于。我感觉是别的问题导致的。比如说，你没有设置dpr=1。用的自动？或者，https://github.com/amfe/article/issues/10 这个问题？

**Comment by chenyulun** [comment]
贴码看一下

**Comment by chenyulun** [comment]
把4年前的文档修改一下，如何防止不触发`Font Boosting`;我正准备用一下这个库做一个新的移动商城

**Comment by imochen** [comment]
```css
*{
max-height:100%
}
```
粗暴处理，加个这个。
