### ISSUE TITLE
希望添加2个参数配置

### ISSUE THREAD

**Issue by chenyulun** [imochen/hotcss#50]
现在发现源码里面有20和320的字样；
应该是在320px宽度的设备上1rem=20px吧
现在设备发展很快啊，我们都是具有iPhone X的375px宽度上开发的，还有我们的希望配置的1rem=50px;
配合 `postcss-pxtorem`插件的`rootValue`:  
如下`postcss.config.js` 配置
```js
const pxtorem = require('postcss-pxtorem')

module.exports = {
  plugins: [
    flexbugsFixes(),
    autoprefixer({
      flexbox: 'no-2009'
      // overrideBrowserslist: ['> 1% in CN', 'android >= 4.4.4', 'ios >= 9', 'not IE 11'] // target = 'desktop'
    }),
    process.env.REM_ENV && pxtorem({
      rootValue: pkgJSon.remUnit, // 配置自动转换的50
      propList: ['*'],
      mediaQuery: true
    })
  ].filter(Boolean)
}
```
然后使用
```html
<meta name="hotcss" rem-unit="50" device-width="375">
```
是否可以呢？

如果你这边改了我以后推广就推广你这个github,不然我自己fork改一下

才发现这个项目fork这么多，魔改的很多啊

**Comment by imochen** [comment]
当下精力不在这块，有兴趣可以提个PR。或者自己Fork一个改改都行。感谢关注。

**Comment by imochen** [comment]
另外 20/320 只是一个比例问题，与设备实际尺寸没有关系。 https://github.com/imochen/hotcss/issues/12
