### ISSUE TITLE
手机横屏后再竖屏渲染不正确

### ISSUE THREAD

**Issue by agileago** [imochen/hotcss#8]
是否考虑在库里面加上手机旋转事件，触发的话自动重新渲染

**Comment by imochen** [comment]
可手动调用`hotcss.mresize()`

**Comment by agileago** [comment]
这个东西应该是库自行处理吧

**Comment by agileago** [comment]
仔细想了想，旋转过来之后应该是触发了resize事件，已经做了调整，但页面部分没有正常渲染，应该是浏览器的问题

**Comment by imochen** [comment]
嗯，可以在这里备注下，机型和浏览器，以便后来者查看，感谢。

**Comment by agileago** [comment]
@imochen  最近发现有的团队是用 

```
<meta name="viewport" content="width=375" />
```

来进行页面的开发，发现也非常完美的适配了所有屏幕，并且直接使用固定值px，而我们还需要用js来控制一下，用sass来进行计算编译，不太理解用上述这种方案和使用hotcss之间有什么不同，你能讲一下区别么？ 并且还能解决有些内容是后台富文本编辑器生成的html排版

**Comment by imochen** [comment]
可以搜下PPK大神关于viewport的文章。
